# Task #08 指定教材 02：在 Python 中實現機器學習
Practice

In [2]:
from sklearn.datasets import load_iris
import pandas as pd

# 載入 iris 資料集
iris = load_iris()

# 轉換為 pandas dataframe
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = iris.target
X,y

(     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
 0                  5.1               3.5                1.4               0.2
 1                  4.9               3.0                1.4               0.2
 2                  4.7               3.2                1.3               0.2
 3                  4.6               3.1                1.5               0.2
 4                  5.0               3.6                1.4               0.2
 ..                 ...               ...                ...               ...
 145                6.7               3.0                5.2               2.3
 146                6.3               2.5                5.0               1.9
 147                6.5               3.0                5.2               2.0
 148                6.2               3.4                5.4               2.3
 149                5.9               3.0                5.1               1.8
 
 [150 rows x 4 columns],
 array([0, 0, 0, 0, 0, 0,

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [4]:
from sklearn.cluster import KMeans

# 建立 KMeans 分群器
kmeans = KMeans(n_clusters=3, random_state=42)

# 對訓練集進行訓練
kmeans.fit(X_train)

KMeans(n_clusters=3, random_state=42)

In [5]:
# 對測試集進行預測
y_pred = kmeans.predict(X_test)

In [6]:
y_pred

array([2, 0, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0, 0, 0, 0, 2, 1, 2, 2, 1, 0, 2,
       0, 1, 1, 1, 1, 1, 0, 0], dtype=int32)

In [7]:
y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [8]:
from sklearn.decomposition import PCA

model = PCA(n_components=2)
X_train_pca = model.fit_transform(X_train)
X_test_pca = model.transform(X_test)

In [9]:
X_test_pca

array([[ 0.96873884, -0.16191895],
       [-2.15827783,  0.87651712],
       [ 3.84073027,  0.29102786],
       [ 0.85922818, -0.14689823],
       [ 1.37724773,  0.26723591],
       [-2.36654757,  0.41251224],
       [-0.12791711, -0.24432722],
       [ 1.96460773,  0.42638905],
       [ 0.99314654, -0.52371424],
       [ 0.18343711, -0.29933501],
       [ 1.70517136,  0.25980183],
       [-2.73929008, -0.23307394],
       [-2.58234715,  0.6013324 ],
       [-2.62643526, -0.11098174],
       [-2.54541161,  0.51346113],
       [ 1.13875122,  0.30044465],
       [ 2.39476265, -0.01909801],
       [ 0.09370154, -0.56856571],
       [ 0.68907607, -0.40116151],
       [ 2.20497517, -0.19721019],
       [-2.5857203 , -0.19543719],
       [ 1.33636405, -0.099865  ],
       [-2.42443591,  0.13153472],
       [ 2.16934852, -0.18887919],
       [ 3.27028025,  1.40411218],
       [ 1.98743146,  0.20484733],
       [ 2.36843897, -0.21717274],
       [ 2.60622076,  0.29951625],
       [-2.66803677,

In [10]:
X_test

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
73                 6.1               2.8                4.7               1.2
18                 5.7               3.8                1.7               0.3
118                7.7               2.6                6.9               2.3
78                 6.0               2.9                4.5               1.5
76                 6.8               2.8                4.8               1.4
31                 5.4               3.4                1.5               0.4
64                 5.6               2.9                3.6               1.3
141                6.9               3.1                5.1               2.3
68                 6.2               2.2                4.5               1.5
82                 5.8               2.7                3.9               1.2
110                6.5               3.2                5.1               2.0
12                 4.8               3.0                1.4               0.1
36                 5.5               3.5                1.3               0.2
9                  4.9               3.1                1.5               0.1
19                 5.1               3.8                1.5               0.3
56                 6.3               3.3                4.7               1.6
104                6.5               3.0                5.8               2.2
69                 5.6               2.5                3.9               1.1
55                 5.7               2.8                4.5               1.3
132                6.4               2.8                5.6               2.2
29                 4.7               3.2                1.6               0.2
127                6.1               3.0                4.9               1.8
26                 5.0               3.4                1.6               0.4
128                6.4               2.8                5.6               2.1
131                7.9               3.8                6.4               2.0
145                6.7               3.0                5.2               2.3
108                6.7               2.5                5.8               1.8
143                6.8               3.2                5.9               2.3
45                 4.8               3.0                1.4               0.3
30                 4.8               3.1                1.6               0.2

In [11]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA

# 讀取手寫數字資料集
digits = load_digits()

# 將特徵與標籤拆開
X = digits.data
y = digits.target

# 切分資料集
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 建立PCA模型，將64維的特徵轉換為2維
model = PCA(n_components=2)
X_train_pca = model.fit_transform(X_train)
X_test_pca = model.transform(X_test)

# 顯示轉換後的訓練集資料
df = pd.DataFrame(data=X_train_pca, columns=['PC1', 'PC2'])
df['target'] = y_train
print(df.head())

         PC1        PC2  target
0  16.468296  19.392492       6
1  -3.066060  22.375263       0
2  13.134396  20.354285       0
3 -22.619749  -5.528615       3
4  -2.003770  23.617267       0


In [13]:
X_train.shape

(1437, 64)

In [14]:
df

PC1        PC2  target
0     16.468296  19.392492       6
1     -3.066060  22.375263       0
2     13.134396  20.354285       0
3    -22.619749  -5.528615       3
4     -2.003770  23.617267       0
...         ...        ...     ...
1432 -26.152349   7.870457       3
1433  -6.835329 -17.537452       7
1434 -13.313760 -10.403266       2
1435   3.079258  -8.808239       7
1436  13.773130 -18.019616       1

[1437 rows x 3 columns]

In [15]:
import pandas as pd
import numpy as np

# 載入波士頓房價資料集
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
features = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

from sklearn.model_selection import train_test_split

# 切割資料集為訓練集和測試集
train_features, test_features, train_target, test_target = train_test_split(features, target, test_size=0.2)

In [16]:
train_features

array([[1.31580e-01, 0.00000e+00, 1.00100e+01, ..., 1.78000e+01,
        3.93300e+02, 1.20400e+01],
       [5.44114e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.55290e+02, 1.77300e+01],
       [5.29305e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.78380e+02, 1.87600e+01],
       ...,
       [2.36482e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.96900e+02, 2.36900e+01],
       [5.57780e-01, 0.00000e+00, 2.18900e+01, ..., 2.12000e+01,
        3.94670e+02, 1.69600e+01],
       [2.63630e-01, 0.00000e+00, 8.56000e+00, ..., 2.09000e+01,
        3.91230e+02, 1.55500e+01]])

In [17]:
import torch
import torch.nn as nn

# 定義自定義模型
class HousePricePredictor(nn.Module):
    def __init__(self, input_size):
        super(HousePricePredictor, self).__init__()
        self.fc1 = nn.Linear(input_size, 64)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(64, 32)
        self.fc3 = nn.Linear(32, 1)
    
    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.relu(x)
        x = self.fc3(x)
        return x

In [18]:
torch.cuda.is_available()

False